### PR TITLE
Time component

### PR DESCRIPTION
**Pull request by sstilesTechtonic**
Here is the time function fully working. I was able to work out all the bugs. Also, I am including the color picker component, but don't have it tied into the time component.

### CODE REVIEW

**Review by Eric-Dunaway — APPROVED** [review]

**Review by Eric-Dunaway — CHANGES_REQUESTED** [review]
please handle merge conflicts

**Comment by sstilesTechtonic** [comment]
> please handle merge conflicts

**Comment by sstilesTechtonic** [comment]
Linter fixed, and merged conflicts are resolved.

**Review by Eric-Dunaway — DISMISSED** [review]
Looks Good

**Review by Eric-Dunaway — APPROVED** [review]
Looks Good

**Pull request merged**
